(() => {
  const U = AUTH.requireRole("teacher");
  if (!U) return;
  const $ = (id) => document.getElementById(id);
  const get = (key, fallback = []) => DG.getData(key, fallback);
  const save = (key, value) => DG.saveData(key, value);
  const fullName = (u) => `${u?.firstName || ""} ${u?.lastName || ""}`.trim() || u?.id || "Unknown";
  const esc = (v) => APP.esc(v ?? "");
  const notify = (studentId, title, message, source, recordId) => {
    const users = get("users", []);
    const targets = users.filter((u) => u.id === studentId || (u.role === "parent" && [u.childId, ...(u.childIds || []), ...(u.children || [])].some((x) => (typeof x === "object" ? x.id || x.studentId : x) === studentId)));
    const ns = get("notifications", []);
    targets.forEach((u) => ns.push({ id: DG.generateId("NOT"), userId: u.id, title, message, date: new Date().toISOString(), read: false, source, [source + "Id"]: recordId }));
    save("notifications", ns);
  };
  const audit = (entity, record, action, notes) => {
    const logs = get("auditLogs", []);
    logs.push({ id: DG.generateId("AUD"), entity, recordId: record.id || `${record.studentId}-${record.subject || record.competency}`, action, actorId: U.id, notes: notes || "", date: new Date().toISOString() });
    save("auditLogs", logs);
  };
  const setup = () => { APP.applyTheme(); APP.updateNotif(); lucide.createIcons(); $("open")?.addEventListener("click", () => $("side")?.classList.toggle("-translate-x-full")); const avatar = $("avatar"); if (avatar) avatar.src = getProfilePhoto(U); };
  const assignmentIds = () => {
    const users = get("users", []), enrollments = get("enrollments", []), grades = get("grades", []), comps = get("competencies", []);
    const ids = new Set(enrollments.filter((e) => e.assignedTeacherId === U.id || e.assignedTeacher === U.id || e.teacherId === U.id).map((e) => e.studentId));
    const teacherName = fullName(U);
    grades.filter((g) => g.teacherId === U.id || g.teacher === teacherName).forEach((g) => ids.add(g.studentId));
    comps.filter((c) => c.teacherId === U.id || c.assessorId === U.id || c.assessor === teacherName).forEach((c) => ids.add(c.studentId));
    return { ids, users, enrollments, grades, comps };
  };
  const studentFor = (id, users = get("users", [])) => users.find((u) => u.id === id);
  const empty = (target, title, text) => { if (target) target.innerHTML = `<tr><td colspan="8" class="p-8 text-center"><div class="font-semibold">${esc(title)}</div><p class="mt-1 text-sm text-slate-400">${esc(text)}</p></td></tr>`; };
  function studentModal(studentId) {
    const { users, enrollments, grades, comps } = assignmentIds(); const s = studentFor(studentId, users); if (!s) return;
    const e = enrollments.filter((x) => x.studentId === studentId).sort((a,b) => String(b.updatedAt || b.createdAt || "").localeCompare(String(a.updatedAt || a.createdAt || "")))[0];
    const modal = document.createElement("div"); modal.className = "fixed inset-0 z-[90] flex items-center justify-center bg-slate-950/50 p-4"; modal.innerHTML = `<div class="max-h-[90vh] w-full max-w-3xl overflow-y-auto rounded-2xl bg-white p-6 shadow-2xl dark:bg-slate-900"><div class="flex items-start justify-between"><div><p class="text-sm text-blue-600">Student record</p><h2 class="text-2xl font-bold">${esc(fullName(s))}</h2><p class="text-sm text-slate-400">${esc(s.id)} · ${esc(s.email || "No email")}</p></div><button class="close text-2xl text-slate-400">×</button></div><div class="mt-6 grid gap-4 sm:grid-cols-2"><div class="rounded-xl bg-slate-50 p-4 dark:bg-slate-800"><p class="text-xs text-slate-400">Strand / Track</p><b>${esc(s.strand || s.track || "—")}</b></div><div class="rounded-xl bg-slate-50 p-4 dark:bg-slate-800"><p class="text-xs text-slate-400">Enrollment</p><b>${esc(e?.status || "No enrollment")}</b><p class="text-xs text-slate-400">${esc([e?.schoolYear, e?.assignedSection].filter(Boolean).join(" · "))}</p></div><div class="rounded-xl bg-slate-50 p-4 dark:bg-slate-800"><p class="text-xs text-slate-400">Requirements</p><b>${get("requirements", []).filter((r) => r.studentId === studentId).length}</b></div><div class="rounded-xl bg-slate-50 p-4 dark:bg-slate-800"><p class="text-xs text-slate-400">Document requests</p><b>${get("documents", []).filter((r) => r.studentId === studentId).length}</b></div></div><h3 class="mt-6 font-bold">Academic records</h3><div class="mt-2 space-y-2">${grades.filter((g) => g.studentId === studentId).map((g) => `<div class="flex justify-between rounded-xl border p-3"><span>${esc(g.subject || "Subject")}</span><b>${g.grade ?? "—"}</b></div>`).join("") || `<p class="text-sm text-slate-400">No grade records.</p>`}</div><h3 class="mt-6 font-bold">Competencies</h3><div class="mt-2 space-y-2">${comps.filter((c) => c.studentId === studentId).map((c) => `<div class="flex justify-between rounded-xl border p-3"><span>${esc(c.competency)}</span><b>${esc(c.status || "Not Started")}</b></div>`).join("") || `<p class="text-sm text-slate-400">No competency records.</p>`}</div></div></div>`;
    modal.querySelector(".close").onclick = () => modal.remove(); modal.onclick = (ev) => { if (ev.target === modal) modal.remove(); }; document.body.append(modal);
  }
  function renderStudents() {
    const { ids, users, enrollments } = assignmentIds(), rows = $("rows"), q = ($( "q")?.value || "").toLowerCase();
    const list = users.filter((s) => s.role === "student" && ids.has(s.id) && `${fullName(s)} ${s.id} ${s.strand || ""}`.toLowerCase().includes(q));
    if (!list.length) return empty(rows, "No assigned students", q ? "Try a different search." : "Students assigned to you will appear here.");
    rows.innerHTML = list.map((s) => { const e = enrollments.find((x) => x.studentId === s.id); return `<tr class="border-t dark:border-slate-800"><td class="p-4 font-semibold">${esc(fullName(s))}</td><td class="p-4 font-mono text-xs">${esc(s.id)}</td><td class="p-4">${esc(s.strand || s.track || "—")}</td><td class="p-4">${APP.statusBadge(e?.status || "No enrollment")}</td><td class="p-4"><button data-student="${esc(s.id)}" class="font-semibold text-green-700">View details</button></td></tr>`; }).join(""); rows.querySelectorAll("[data-student]").forEach((b) => b.onclick = () => studentModal(b.dataset.student));
  }
  function injectSearch(id, placeholder, oninput) { if ($(id)) return; const main = document.querySelector("main .max-w-7xl") || document.querySelector("main"); const box = document.createElement("div"); box.className = "card mb-5 grid gap-3 p-4 md:grid-cols-3"; box.innerHTML = `<input id="teacherSearch" class="input rounded-xl border px-4 py-3 md:col-span-2" placeholder="${placeholder}"><select id="teacherFilter" class="input rounded-xl border px-4 py-3"><option value="">All records</option></select><div class="flex gap-2 md:col-span-3"><button id="teacherExport" type="button" class="rounded-xl border px-4 py-2 text-sm font-semibold">Export CSV</button><button id="teacherBulk" type="button" class="hidden rounded-xl bg-green-600 px-4 py-2 text-sm font-semibold text-white">Update visible</button></div>`; main.querySelector(".mb-7")?.after(box); $("teacherSearch").oninput = oninput; $("teacherExport").onclick = () => exportVisible(); $("teacherBulk").onclick = () => bulkCompetencies(); }
  function downloadCsv(name, rows) { const csv = rows.map((r) => r.map((v) => `"${String(v ?? "").replaceAll('"', '""')}"`).join(",")).join("\n"); const a = document.createElement("a"); a.href = URL.createObjectURL(new Blob([csv], { type: "text/csv" })); a.download = name; a.click(); URL.revokeObjectURL(a.href); }
  function exportVisible() { const page = location.pathname.split("/").pop(); const data = assignmentIds(); const q = ($("teacherSearch")?.value || "").toLowerCase(); if (page === "grades.html") { const rows = data.grades.filter((g) => data.ids.has(g.studentId) && (!q || `${fullName(studentFor(g.studentId, data.users))} ${g.studentId} ${g.subject || ""}`.toLowerCase().includes(q))).map((g) => [fullName(studentFor(g.studentId, data.users)), g.studentId, g.subject, g.grade ?? "", g.remarks || "", g.term || g.period || "", g.published ? "Published" : "Unpublished"]); downloadCsv("teacher-grades.csv", [["Student", "Student ID", "Subject", "Grade", "Remarks", "Term", "Publication"], ...rows]); } else if (page === "competencies.html") { const rows = data.comps.filter((c) => data.ids.has(c.studentId) && (!q || `${fullName(studentFor(c.studentId, data.users))} ${c.studentId} ${c.competency || ""}`.toLowerCase().includes(q))).map((c) => [fullName(studentFor(c.studentId, data.users)), c.studentId, c.competency, c.qualification, c.status, c.assessmentDate, c.assessor, c.remarks, c.evidence]); downloadCsv("teacher-competencies.csv", [["Student", "Student ID", "Competency", "Qualification", "Status", "Assessment Date", "Assessor", "Remarks", "Evidence"], ...rows]); } else { const rows = data.users.filter((s) => s.role === "student" && data.ids.has(s.id)).map((s) => [fullName(s), s.id, s.strand || s.track || ""]); downloadCsv("teacher-students.csv", [["Student", "Student ID", "Strand"], ...rows]); } APP.toast("CSV exported"); }
  function bulkCompetencies() { const data = assignmentIds(); const q = ($("teacherSearch")?.value || "").toLowerCase(); const list = data.comps.filter((c) => data.ids.has(c.studentId) && (!q || `${fullName(studentFor(c.studentId, data.users))} ${c.studentId} ${c.competency || ""}`.toLowerCase().includes(q))); const status = window.prompt("Set visible records to: Not Started, In Progress, Competent, or Not Yet Competent", "In Progress"); if (!["Not Started", "In Progress", "Competent", "Not Yet Competent"].includes(status)) return; if (!window.confirm(`Update ${list.length} visible competency records to ${status}?`)) return; const all = get("competencies", []); list.forEach((item) => { const c = all.find((x) => x.id === item.id); if (c) { c.status = status; c.assessmentDate = new Date().toISOString().slice(0, 10); c.updatedAt = new Date().toISOString(); c.updatedBy = U.id; audit("competency", c, "Bulk assessment update", `Status set to ${status}`); notify(c.studentId, `Competency ${status}`, `${c.competency || "Competency"} was updated to ${status}.`, "competency", c.id); } }); save("competencies", all); APP.toast(`${list.length} assessment${list.length === 1 ? "" : "s"} updated`); renderCompetencies(); }
  function renderGrades() {
    const { ids, users, grades } = assignmentIds(), tbody = $("rows"), q = ($("teacherSearch")?.value || "").toLowerCase(), filter = $("teacherFilter")?.value || "";
    const list = grades.filter((g) => ids.has(g.studentId) && (!q || `${fullName(studentFor(g.studentId, users))} ${g.studentId} ${g.subject || ""}`.toLowerCase().includes(q)) && (!filter || (g.published ? "Published" : "Unpublished") === filter));
    if (!list.length) return empty(tbody, "No assigned grade records", "Grades for your assigned students will appear here.");
    tbody.innerHTML = list.map((g) => { const s = studentFor(g.studentId, users); return `<tr class="border-t dark:border-slate-800"><td class="p-4">${esc(fullName(s) || g.studentId)}</td><td class="p-4 font-semibold">${esc(g.subject || "—")}</td><td class="p-4"><input data-grade="${esc(g.id)}" value="${g.grade ?? ""}" type="number" min="0" max="100" step="0.01" class="input w-24 rounded-lg border px-2 py-1.5"></td><td class="p-4"><select data-remark="${esc(g.id)}" class="input rounded-lg border px-2 py-1.5"><option ${g.remarks === "Passed" ? "selected" : ""}>Passed</option><option ${g.remarks === "Failed" ? "selected" : ""}>Failed</option></select></td><td class="p-4"><input data-term="${esc(g.id)}" value="${esc(g.term || g.period || "")}" placeholder="Term" class="input w-24 rounded-lg border px-2 py-1.5"></td><td class="p-4"><select data-published="${esc(g.id)}" class="input rounded-lg border px-2 py-1.5"><option value="false" ${!g.published ? "selected" : ""}>Unpublished</option><option value="true" ${g.published ? "selected" : ""}>Published</option></select></td><td class="p-4"><button data-save-grade="${esc(g.id)}" class="font-semibold text-green-700">Save</button><p class="mt-1 text-[11px] text-slate-400">${esc(APP.formatDate(g.updatedAt))}</p></td></tr>`; }).join(""); tbody.querySelectorAll("[data-save-grade]").forEach((b) => b.onclick = () => saveGrade(b.dataset.saveGrade));
  }
  function saveGrade(id) { const all = get("grades", []), g = all.find((x) => x.id === id); const value = $("teacherSearch") ? document.querySelector(`[data-grade="${CSS.escape(id)}"]`) : null; if (!g || !value) return; const n = value.value === "" ? null : Number(value.value); if (n !== null && (!Number.isFinite(n) || n < 0 || n > 100)) return APP.toast("Grade must be between 0 and 100", "error"); g.grade = n; g.remarks = document.querySelector(`[data-remark="${CSS.escape(id)}"]`).value; if (n !== null) g.remarks = n >= 75 ? "Passed" : "Failed"; g.term = document.querySelector(`[data-term="${CSS.escape(id)}"]`).value.trim(); g.period = g.term; g.published = document.querySelector(`[data-published="${CSS.escape(id)}"]`).value === "true"; g.updatedAt = new Date().toISOString(); g.updatedBy = U.id; save("grades", all); audit("grade", g, "Grade updated", `Saved ${g.grade ?? "blank"} / ${g.remarks}`); notify(g.studentId, `Grade ${g.published ? "published" : "updated"}`, `${g.subject || "A subject"} grade was updated.`, "grade", g.id); APP.toast("Grade saved"); renderGrades(); }
  function renderCompetencies() { const { ids, users, comps } = assignmentIds(), cards = $("cards"), q = ($("teacherSearch")?.value || "").toLowerCase(), filter = $("teacherFilter")?.value || ""; const list = comps.filter((c) => ids.has(c.studentId) && (!q || `${fullName(studentFor(c.studentId, users))} ${c.studentId} ${c.competency || ""}`.toLowerCase().includes(q)) && (!filter || (c.status || "Not Started") === filter)); if (!list.length) { cards.innerHTML = `<div class="card p-8 text-center"><b>No assigned competency records</b><p class="mt-1 text-sm text-slate-400">Assessments for your assigned students will appear here.</p></div>`; return; } cards.innerHTML = list.map((c) => `<div class="card flex flex-col justify-between gap-4 p-5 lg:flex-row lg:items-center"><div><p class="text-xs text-slate-400">${esc(fullName(studentFor(c.studentId, users)))} · ${esc(c.studentId)}</p><b>${esc(c.competency || "Competency")}</b><p class="text-sm text-slate-500">${esc(c.qualification || "")} · ${esc(c.status || "Not Started")}</p><p class="text-xs text-slate-400">Assessed: ${esc(APP.formatDate(c.assessmentDate))} ${c.assessor ? `· ${esc(c.assessor)}` : ""}</p><p class="mt-1 text-xs text-slate-500">${esc(c.remarks || c.evidence || "No remarks or evidence added")}</p></div><button data-edit-comp="${esc(c.id)}" class="rounded-xl bg-green-600 px-4 py-2 font-semibold text-white">Edit assessment</button></div>`).join(""); cards.querySelectorAll("[data-edit-comp]").forEach((b) => b.onclick = () => editCompetency(b.dataset.editComp)); }
  function editCompetency(id) { const all = get("competencies", []), c = all.find((x) => x.id === id); if (!c) return; const root = $("modalRoot"); root.innerHTML = `<div class="fixed inset-0 z-[90] flex items-center justify-center bg-slate-950/50 p-4"><form id="compForm" class="w-full max-w-lg rounded-2xl bg-white p-6 shadow-2xl dark:bg-slate-900"><div class="flex justify-between"><h2 class="text-xl font-bold">Update competency assessment</h2><button type="button" id="closeComp" class="text-2xl text-slate-400">×</button></div><p class="mt-2 text-sm text-slate-500">${esc(c.competency)} · ${esc(c.studentId)}</p><label class="mt-5 block text-sm font-semibold">Status<select id="compStatus" class="input mt-1 w-full rounded-xl border px-3 py-2"><option>Not Started</option><option>In Progress</option><option>Competent</option><option>Not Yet Competent</option></select></label><label class="mt-3 block text-sm font-semibold">Assessment date<input id="compDate" type="date" class="input mt-1 w-full rounded-xl border px-3 py-2"></label><label class="mt-3 block text-sm font-semibold">Assessor<input id="compAssessor" class="input mt-1 w-full rounded-xl border px-3 py-2"></label><label class="mt-3 block text-sm font-semibold">Evidence<textarea id="compEvidence" class="input mt-1 w-full rounded-xl border px-3 py-2"></textarea></label><label class="mt-3 block text-sm font-semibold">Remarks<textarea id="compRemarks" class="input mt-1 w-full rounded-xl border px-3 py-2"></textarea></label><button class="mt-5 w-full rounded-xl bg-green-600 px-4 py-3 font-semibold text-white">Save assessment</button></form></div>`; $("compStatus").value = c.status || "Not Started"; $("compDate").value = c.assessmentDate ? String(c.assessmentDate).slice(0,10) : new Date().toISOString().slice(0,10); $("compAssessor").value = c.assessor || fullName(U); $("compEvidence").value = c.evidence || ""; $("compRemarks").value = c.remarks || ""; $("closeComp").onclick = () => root.innerHTML = ""; $("compForm").onsubmit = (ev) => { ev.preventDefault(); const from = c.status || "Not Started"; Object.assign(c, { status: $("compStatus").value, assessmentDate: $("compDate").value, assessor: $("compAssessor").value.trim(), evidence: $("compEvidence").value.trim(), remarks: $("compRemarks").value.trim(), updatedAt: new Date().toISOString(), updatedBy: U.id }); save("competencies", all); audit("competency", c, "Assessment updated", `${from} → ${c.status}`); notify(c.studentId, `Competency ${c.status}`, `${c.competency || "Competency"} was updated to ${c.status}.`, "competency", c.id); root.innerHTML = ""; APP.toast("Assessment saved"); renderCompetencies(); }; }
  function dashboard() { const { ids, grades, comps } = assignmentIds(); const shortcuts = document.querySelectorAll("main .card"); shortcuts.forEach((card) => { const label = card.textContent || ""; if (label.includes("Assigned Students") && !card.querySelector("a")) card.insertAdjacentHTML("beforeend", `<a href="students.html" class="mt-4 inline-flex text-sm font-semibold text-green-700">Open students →</a>`); if (label.includes("Pending Grades") && !card.querySelector("a")) card.insertAdjacentHTML("beforeend", `<a href="grades.html" class="mt-4 inline-flex text-sm font-semibold text-green-700">Review grades →</a>`); if (label.includes("Competency Assessments") && !card.querySelector("a")) card.insertAdjacentHTML("beforeend", `<a href="competencies.html" class="mt-4 inline-flex text-sm font-semibold text-green-700">Review assessments →</a>`); }); const students = $("students"), pending = $("pending"), count = $("comps"), notifs = $("notifs"), list = $("list"); if (students) students.textContent = ids.size; if (pending) pending.textContent = grades.filter((g) => ids.has(g.studentId) && (g.grade === null || g.grade === undefined || g.grade === "")).length; if (count) count.textContent = comps.filter((c) => ids.has(c.studentId)).length; if (notifs) notifs.textContent = get("notifications", []).filter((n) => n.userId === U.id && !n.read).length; const summary = document.querySelector("main .max-w-7xl > .mb-7"); if (summary && !$("teacherSync")) { const sync = document.createElement("p"); sync.id = "teacherSync"; sync.className = "mt-2 text-xs text-slate-400"; sync.textContent = `Last refreshed ${new Date().toLocaleTimeString()}`; summary.append(sync); } const users = get("users", []); if (list) { const assigned = users.filter((s) => ids.has(s.id)).slice(0, 6); list.innerHTML = assigned.length ? assigned.map((s) => `<div class="rounded-xl border p-4 flex justify-between"><div><b>${esc(fullName(s))}</b><p class="text-xs text-slate-400">${esc(s.id)}</p></div><button data-student="${esc(s.id)}" class="text-sm font-semibold text-green-700">Open</button></div>`).join("") : `<p class="text-sm text-slate-400">No students are assigned to you yet.</p>`; list.querySelectorAll("[data-student]").forEach((b) => b.onclick = () => studentModal(b.dataset.student)); } }
  function profile() { const fields = { nm: fullName(U), id: U.id, dept: U.department || "Faculty", firstName: U.firstName, lastName: U.lastName, email: U.email, specialization: U.specialization || "" }; Object.entries(fields).forEach(([k,v]) => { if ($(k)) $(k).value !== undefined ? ($(k).value = v) : ($(k).textContent = v); }); if ($("av")) $("av").src = getProfilePhoto(U); const input = document.createElement("input"); input.type = "file"; input.accept = "image/*"; input.className = "mt-4 block text-sm"; input.id = "teacherPhoto"; $("specialization")?.parentElement?.after(input); $("teacherPhoto").onchange = () => { const file = $("teacherPhoto").files[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => { DG.setProfilePhoto(reader.result, U); if ($("avatar")) $("avatar").src = reader.result; if ($("av")) $("av").src = reader.result; APP.toast("Profile photo updated"); }; reader.readAsDataURL(file); }; window.save = saveProfile; }
  function saveProfile() { const all = get("users", []), u = all.find((x) => x.id === U.id); if (!u) return; u.specialization = $("specialization")?.value.trim() || ""; u.phone = $("phone")?.value.trim() || u.phone || ""; save("users", all); DG.setCurrentUser(u); APP.toast("Profile updated"); }
  setup(); const page = location.pathname.split("/").pop(); if (page === "dashboard.html") dashboard(); if (page === "students.html") { injectSearch("teacherSearch", "Search assigned students", renderStudents); $("q")?.remove(); renderStudents(); } if (page === "grades.html") { injectSearch("teacherSearch", "Search student, ID, or subject", renderGrades); $("teacherFilter").innerHTML = `<option value="">All publication states</option><option>Published</option><option>Unpublished</option>`; $("teacherFilter").onchange = renderGrades; renderGrades(); } if (page === "competencies.html") { injectSearch("teacherSearch", "Search student, ID, or competency", renderCompetencies); $("teacherBulk").classList.remove("hidden"); $("teacherFilter").innerHTML = `<option value="">All statuses</option><option>Not Started</option><option>In Progress</option><option>Competent</option><option>Not Yet Competent</option>`; $("teacherFilter").onchange = renderCompetencies; renderCompetencies(); } if (page === "profile.html") profile();
})();
