const DEMO = {
  users: [
    {
      id: "ADM-2026-000001",
      role: "admin",
      firstName: "System",
      lastName: "Administrator",
      email: "admin@digitech.local",
      username: "admin",
      password: "Admin@123",
      department: "Administration",
    },
    {
      id: "TCH-2026-000001",
      role: "teacher",
      firstName: "Maria",
      lastName: "Santos",
      email: "teacher@digitech.local",
      username: "teacher",
      password: "Teacher@123",
      department: "ICT",
      specialization: "Programming",
    },
    {
      id: "STU-2026-000001",
      role: "student",
      firstName: "Kim Philip",
      middleName: "",
      lastName: "Lonzame",
      email: "student@digitech.local",
      username: "student",
      password: "Student@123",
      contact: "09171234567",
      birthDate: "2005-06-12",
      address: "Laguna, Philippines",
      guardianName: "Juan Lonzame",
      guardianContact: "09170000000",
      strand: "ICT",
      track: "TVL-ICT",
    },
  ],
  enrollments: [
    {
      id: "ENR-2026-001",
      studentId: "STU-2026-000001",
      status: "Submitted",
      programType: "Senior High",
      gradeLevel: "Grade 12",
      strand: "ICT",
      track: "TVL-ICT",
      schoolYear: "2026-2027",
      updatedAt: "2026-08-28",
    },
  ],
  requirements: [
    {
      id: "REQ-2026-001",
      studentId: "STU-2026-000001",
      name: "Birth Certificate",
      status: "Submitted",
      dateSubmitted: "2026-08-20",
    },
    {
      id: "REQ-2026-002",
      studentId: "STU-2026-000001",
      name: "Report Card",
      status: "Verified",
      dateSubmitted: "2026-08-21",
    },
    {
      id: "REQ-2026-003",
      studentId: "STU-2026-000001",
      name: "Good Moral Certificate",
      status: "Pending",
      dateSubmitted: null,
    },
    {
      id: "REQ-2026-004",
      studentId: "STU-2026-000001",
      name: "Valid ID",
      status: "Pending",
      dateSubmitted: null,
    },
  ],
  documentRequests: [
    {
      id: "DOC-2026-001",
      studentId: "STU-2026-000001",
      documentType: "Transcript of Records",
      purpose: "Scholarship application",
      copies: 1,
      notes: "Certified copy",
      requestDate: "2026-08-27",
      status: "Processing",
    },
    {
      id: "DOC-2026-002",
      studentId: "STU-2026-000001",
      documentType: "Good Moral Certificate",
      purpose: "Employment requirement",
      copies: 2,
      notes: "",
      requestDate: "2026-08-25",
      status: "Ready for Release",
    },
  ],
  grades: [
    {
      id: "GRD-2026-001",
      studentId: "STU-2026-000001",
      subject: "Mathematics",
      code: "MATH12",
      teacher: "Maria Santos",
      semester: "1st Semester",
      schoolYear: "2026-2027",
      grade: 1.5,
      remarks: "Passed",
    },
    {
      id: "GRD-2026-002",
      studentId: "STU-2026-000001",
      subject: "English",
      code: "ENG12",
      teacher: "Maria Santos",
      semester: "1st Semester",
      schoolYear: "2026-2027",
      grade: 1.75,
      remarks: "Passed",
    },
    {
      id: "GRD-2026-003",
      studentId: "STU-2026-000001",
      subject: "Programming",
      code: "PROG12",
      teacher: "Maria Santos",
      semester: "1st Semester",
      schoolYear: "2026-2027",
      grade: 1.25,
      remarks: "Passed",
    },
  ],
  competencies: [
    {
      id: "CMP-2026-001",
      studentId: "STU-2026-000001",
      qualification: "Computer Systems Servicing NC II",
      competency: "Install and Configure Computer Systems",
      status: "Competent",
      assessmentDate: "2026-07-12",
      remarks: "Passed practical assessment",
    },
    {
      id: "CMP-2026-002",
      studentId: "STU-2026-000001",
      qualification: "Computer Systems Servicing NC II",
      competency: "Set Up Computer Networks",
      status: "Competent",
      assessmentDate: "2026-07-19",
      remarks: "Passed",
    },
    {
      id: "CMP-2026-003",
      studentId: "STU-2026-000001",
      qualification: "Computer Systems Servicing NC II",
      competency: "Perform Computer Maintenance",
      status: "In Progress",
      assessmentDate: "2026-08-10",
      remarks: "Final assessment pending",
    },
    {
      id: "CMP-2026-004",
      studentId: "STU-2026-000001",
      qualification: "Computer Systems Servicing NC II",
      competency: "Test Electronic Components",
      status: "Not Started",
      assessmentDate: "",
      remarks: "",
    },
  ],
  notifications: [
    {
      id: "NTF-1",
      userId: "STU-2026-000001",
      title: "Enrollment submitted",
      message: "Your enrollment application is now under review.",
      date: "2026-08-28T09:30:00",
      read: false,
    },
    {
      id: "NTF-2",
      userId: "STU-2026-000001",
      title: "Document request updated",
      message: "Your TOR request is being processed.",
      date: "2026-08-27T15:10:00",
      read: false,
    },
    {
      id: "NTF-3",
      userId: "TCH-2026-000001",
      title: "New student activity",
      message: "A student has submitted enrollment information.",
      date: "2026-08-28T08:20:00",
      read: false,
    },
  ],
};
function seedData() {
  if (localStorage.getItem("digitech_seeded")) return;
  Object.entries(DEMO).forEach(([k, v]) => DG.saveData(k, v));
  DG.saveData("settings", {
    theme: "light",
    teacherRegistration: true,
    adminRegistration: false,
  });
  localStorage.setItem("digitech_seeded", "1");
}
seedData();
